// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Cach struct {
	ID             string
	Name           string
	CreatedAt      string
	LastAccessedAt sql.NullString
	UpdatedAt      string
}

type CacheNar struct {
	CacheID   string
	NarID     string
	CreatedAt string
}

type Chunk struct {
	ID              string
	ChunkHash       string
	Size            int64
	CompressionType sql.NullString
	S3Key           string
	Etag            string
	CreatedAt       string
}

type Nar struct {
	ID             string
	StorePath      string
	NarHash        string
	NarSize        int64
	ChunkCount     int64
	CreatedAt      string
	LastAccessedAt sql.NullString
	UpdatedAt      string
}

type NarChunk struct {
	NarID      string
	ChunkID    string
	ChunkIndex int64
	Offset     int64
	CreatedAt  string
}
